apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-helm-simple-analysis
  namespace: kargo-helm
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
          annotations:
            analysis: kargo-helm-simple-analysis
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "0"
                imagePullPolicy: IfNotPresent
              restartPolicy: Never